version: "3.8"

services:
  electrify-chicago:
    image: electrify-chicago:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn develop
