[build]
  command = "yarn build"  # Your main build command

[build.environment]
  PYTHON_VERSION = "3.12.0"  # Using Python 3.12
  NODE_VERSION = "20"        # Use compatible version from package.json

  # Skip requirements.txt installation
  NETLIFY_USE_YARN = "true"
  NETLIFY_RESTORE_PYTHON = "false"  # Prevent automatic Python setup
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
