[project]
name = "electrify-chicago"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "python-slugify",
    "pandas",
    "numpy",
    "pytest",
    "plotly",
    "statsmodels",
    "nbformat",
    "jupyter",
    "ipykernel",
    "pip",
    "pytest"
]

[project.optional-dependencies]
notebook = [
    "kaleido",
    "jupyterlab",
    "matplotlib",
    "ipywidgets",
    "nbconvert",
    "jupyter",
    "ipykernel"
]
